### ISSUE TITLE
Finish replicate study

### ISSUE THREAD

**Issue by rampage644** [rampage644/memn2n-tensorflow#1]
## TODO

* [x] Basic memn2n-bAbI  implementation
* [ ] Basi memn2n language model implementation
* [ ] Implement linear start
* [ ] Implement random noise
* [x] Checkpoint of our model
* [ ] _Tune (improve)_ MemN2N implementation
* [ ] Present results in nice visual way
